/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package myswingapp;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author hp
 */
public class adminlogin extends javax.swing.JFrame {

    /**
     * Creates new form adminlogin
     */
    public adminlogin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        adminlog = new javax.swing.JPanel();
        shopname = new javax.swing.JLabel();
        btnadmin = new javax.swing.JButton();
        btnstudent = new javax.swing.JButton();
        lblreg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        adminlog.setBackground(new java.awt.Color(250, 235, 214));

        shopname.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        shopname.setForeground(new java.awt.Color(255, 0, 0));
        shopname.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        shopname.setText("Programmers Point");

        btnadmin.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        btnadmin.setForeground(new java.awt.Color(255, 0, 51));
        btnadmin.setText("Admin login");
        btnadmin.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnadmin.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnadminActionPerformed(evt);
            }
        });

        btnstudent.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        btnstudent.setForeground(new java.awt.Color(255, 51, 0));
        btnstudent.setText("Student login");
        btnstudent.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnstudent.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnstudentActionPerformed(evt);
            }
        });

        lblreg.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblreg.setForeground(new java.awt.Color(255, 51, 0));
        lblreg.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblreg.setText("If you dont have the login id and password please visit the center and register with admin");
        lblreg.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout adminlogLayout = new javax.swing.GroupLayout(adminlog);
        adminlog.setLayout(adminlogLayout);
        adminlogLayout.setHorizontalGroup(
            adminlogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(adminlogLayout.createSequentialGroup()
                .addGroup(adminlogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(adminlogLayout.createSequentialGroup()
                        .addGroup(adminlogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(adminlogLayout.createSequentialGroup()
                                .addGap(87, 87, 87)
                                .addComponent(shopname, javax.swing.GroupLayout.PREFERRED_SIZE, 448, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(adminlogLayout.createSequentialGroup()
                                .addGap(153, 153, 153)
                                .addGroup(adminlogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(btnadmin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnstudent, javax.swing.GroupLayout.DEFAULT_SIZE, 315, Short.MAX_VALUE))))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(lblreg, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 608, Short.MAX_VALUE))
                .addContainerGap())
        );
        adminlogLayout.setVerticalGroup(
            adminlogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(adminlogLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(shopname, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(53, 53, 53)
                .addComponent(btnadmin, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnstudent, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                .addComponent(lblreg, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(adminlog, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(adminlog, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnadminActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnadminActionPerformed
    {//GEN-HEADEREND:event_btnadminActionPerformed
        // TODO add your handling code here:
        String path="jdbc:mysql://localhost:3306/student";
        try
        {
            Connection con=DriverManager.getConnection(path,"root","root");
            
                new ad1().setVisible(true);
                dispose();
            
        }
        catch(SQLException ex)
        {
            System.out.println("error"+ex);
        }
    }//GEN-LAST:event_btnadminActionPerformed

    private void btnstudentActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnstudentActionPerformed
    {//GEN-HEADEREND:event_btnstudentActionPerformed
        // TODO add your handling code here:
        String path="jdbc:mysql://localhost:3306/student";
        try
        {
            Connection con=DriverManager.getConnection(path,"root","root");
            
                new Stu2().setVisible(true);
                dispose();
            
        }
        catch(SQLException ex)
        {
            System.out.println("error"+ex);
        }
    }//GEN-LAST:event_btnstudentActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(adminlogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(adminlogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(adminlogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(adminlogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new adminlogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel adminlog;
    private javax.swing.JButton btnadmin;
    private javax.swing.JButton btnstudent;
    private javax.swing.JLabel lblreg;
    private javax.swing.JLabel shopname;
    // End of variables declaration//GEN-END:variables
}
