/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package myswingapp;

import java.io.IOException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;

/**
 *
 * @author hp
 */
public class cselect extends javax.swing.JFrame
{

    /**
     * Creates new form cselect
     */
    public cselect()
    {
        initComponents();
        addWindowListener(new WindowClose(new Stu2()));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        btnchp1 = new javax.swing.JButton();
        btnchp2 = new javax.swing.JButton();
        btnchp3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(251, 241, 227));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Select required chapter");

        btnchp1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnchp1.setForeground(new java.awt.Color(255, 51, 51));
        btnchp1.setText("Chapter 1");
        btnchp1.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnchp1ActionPerformed(evt);
            }
        });

        btnchp2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnchp2.setForeground(new java.awt.Color(255, 51, 51));
        btnchp2.setText("Chapter 2");
        btnchp2.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnchp2ActionPerformed(evt);
            }
        });

        btnchp3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnchp3.setForeground(new java.awt.Color(255, 51, 51));
        btnchp3.setText("Chapter 3");
        btnchp3.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnchp3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(80, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(57, 57, 57))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(149, 149, 149)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnchp1, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnchp2, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnchp3, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(jLabel2)
                .addGap(35, 35, 35)
                .addComponent(btnchp1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnchp2, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnchp3, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(62, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnchp1ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnchp1ActionPerformed
    {//GEN-HEADEREND:event_btnchp1ActionPerformed
        // TODO add your handling code here:
        try
        {
            String sql;
            PreparedStatement st;
            ResultSet rs;
            Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/student","root","root");
            sql="select path3 from cnotes where id =1";
            st=con.prepareStatement(sql);
            rs=st.executeQuery();
            if(rs.next())
            {
                String add1=rs.getString("path3");
                Runtime rt=Runtime.getRuntime();
                try
                {
                    Process p=rt.exec("notepad "+add1);
                } 
                catch(IOException ex)
                {
                    System.out.println("error"+ex);
                }
            }
        }
        catch(SQLException e)
        {
            System.out.println("error"+e);
        }
    }//GEN-LAST:event_btnchp1ActionPerformed

    private void btnchp2ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnchp2ActionPerformed
    {//GEN-HEADEREND:event_btnchp2ActionPerformed
        // TODO add your handling code here:
        try
        {
            String sql;
            PreparedStatement st;
            ResultSet rs;
            Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/student","root","root");
            sql="select path3 from cnotes where id =2";
            st=con.prepareStatement(sql);
            rs=st.executeQuery();
            if(rs.next())
            {
                String add1=rs.getString("path3");
                Runtime rt=Runtime.getRuntime();
                try
                {
                    Process p=rt.exec("notepad "+add1);
                } 
                catch(IOException ex)
                {
                    System.out.println("error"+ex);
                }
            }
        }
        catch(SQLException e)
        {
            System.out.println("error"+e);
        }
    }//GEN-LAST:event_btnchp2ActionPerformed

    private void btnchp3ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnchp3ActionPerformed
    {//GEN-HEADEREND:event_btnchp3ActionPerformed
        // TODO add your handling code here:
        try
        {
            String sql;
            PreparedStatement st;
            ResultSet rs;
            Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/student","root","root");
            sql="select path3 from cnotes where id =3";
            st=con.prepareStatement(sql);
            rs=st.executeQuery();
            if(rs.next())
            {
                String add1=rs.getString("path3");
                Runtime rt=Runtime.getRuntime();
                try
                {
                    Process p=rt.exec("notepad "+add1);
                } 
                catch(IOException ex)
                {
                    System.out.println("error"+ex);
                }
            }
        }
        catch(SQLException e)
        {
            System.out.println("error"+e);
        }
    }//GEN-LAST:event_btnchp3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(cselect.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(cselect.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(cselect.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(cselect.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {
                new cselect().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnchp1;
    private javax.swing.JButton btnchp2;
    private javax.swing.JButton btnchp3;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
