/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package myswingapp;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author hp
 */
public class Remstu extends javax.swing.JFrame
{

    /**
     * Creates new form Remstu
     */
    public Remstu()
    {
        initComponents();
        addWindowListener(new WindowClose(new ad2()));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jPanel1 = new javax.swing.JPanel();
        lblh2 = new javax.swing.JLabel();
        txtfname = new javax.swing.JTextField();
        btnremove = new javax.swing.JButton();
        lblh3 = new javax.swing.JLabel();
        txtlname = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(251, 241, 227));

        lblh2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblh2.setForeground(new java.awt.Color(255, 51, 0));
        lblh2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblh2.setText("Enter fname");

        txtfname.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtfname.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtfname.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                txtfnameActionPerformed(evt);
            }
        });

        btnremove.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnremove.setForeground(new java.awt.Color(255, 0, 0));
        btnremove.setText("Delete");
        btnremove.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnremoveActionPerformed(evt);
            }
        });

        lblh3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblh3.setForeground(new java.awt.Color(255, 51, 0));
        lblh3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblh3.setText("Enter surname");

        txtlname.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtlname.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblh3)
                    .addComponent(lblh2, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnremove)
                    .addComponent(txtlname, javax.swing.GroupLayout.DEFAULT_SIZE, 210, Short.MAX_VALUE)
                    .addComponent(txtfname))
                .addGap(52, 52, 52))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtfname, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblh2, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtlname, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblh3, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addComponent(btnremove, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(57, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnremoveActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnremoveActionPerformed
    {//GEN-HEADEREND:event_btnremoveActionPerformed
        // TODO add your handling code here:
        /*try
        {
            Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/student","root","root");
            String sql="delete from stud where fname =? and lname =?";
            PreparedStatement st=con.prepareStatement(sql);
            st.setString(1,txtfname.getText());
            st.setString(2,txtlname.getText());
            st.execute();
            JOptionPane.showMessageDialog(null,"Student removed successfully");
        }
        catch(SQLException ex)
        {
            System.out.println("delete error"+ex);
        }*/
        try
        {
            Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/student","root","root");
            String sql,s1,s2,s3;
            ResultSet rs;
            PreparedStatement st;
            s1="select * from java where fname =? and lname=?";
            st=con.prepareStatement(s1);
            st.setString(1,txtfname.getText());
            st.setString(2,txtlname.getText());
            rs=st.executeQuery();
            if(rs.next())
            {
                sql="delete from java where fname =? and lname =?";
                st=con.prepareStatement(sql);
                st.setString(1,txtfname.getText());
                st.setString(2,txtlname.getText());
                st.execute();
            }
            s1="select * from python where fname =? and lname=?";
            st=con.prepareStatement(s1);
            st.setString(1,txtfname.getText());
            st.setString(2,txtlname.getText());
            rs=st.executeQuery();
            if(rs.next())
            {
                sql="delete from python where fname =? and lname =?";
                st=con.prepareStatement(sql);
                st.setString(1,txtfname.getText());
                st.setString(2,txtlname.getText());
                st.execute();
            }
            s1="select * from c where fname =? and lname=?";
            st=con.prepareStatement(s1);
            st.setString(1,txtfname.getText());
            st.setString(2,txtlname.getText());
            rs=st.executeQuery();
            if(rs.next())
            {
                sql="delete from c where fname =? and lname =?";
                st=con.prepareStatement(sql);
                st.setString(1,txtfname.getText());
                st.setString(2,txtlname.getText());
                st.execute();
            }
            sql="delete from stud where fname =? and lname =?";
            st=con.prepareStatement(sql);
            st.setString(1,txtfname.getText());
            st.setString(2,txtlname.getText());
            st.execute();
            JOptionPane.showMessageDialog(null,"Student removed successfully");
        }
        catch(SQLException ex)
        {
            System.out.println("delete error"+ex);
        }
    }//GEN-LAST:event_btnremoveActionPerformed

    private void txtfnameActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_txtfnameActionPerformed
    {//GEN-HEADEREND:event_txtfnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtfnameActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(Remstu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(Remstu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(Remstu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(Remstu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {
                new Remstu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnremove;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblh2;
    private javax.swing.JLabel lblh3;
    private javax.swing.JTextField txtfname;
    private javax.swing.JTextField txtlname;
    // End of variables declaration//GEN-END:variables
}
