/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package myswingapp;

import java.io.IOException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author hp
 */
public class Stu2 extends javax.swing.JFrame
{

    /**
     * Creates new form Stu2
     */
    public Stu2()
    {
        initComponents();
        addWindowListener(new WindowClose(new adminlogin()));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jPanel1 = new javax.swing.JPanel();
        btnjava = new javax.swing.JButton();
        btnpython = new javax.swing.JButton();
        btnc = new javax.swing.JButton();
        lblh1 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txtfname = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtlname = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(251, 241, 227));

        btnjava.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnjava.setForeground(new java.awt.Color(255, 0, 0));
        btnjava.setText("JAVA");
        btnjava.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnjavaActionPerformed(evt);
            }
        });

        btnpython.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnpython.setForeground(new java.awt.Color(255, 0, 0));
        btnpython.setText("Python");
        btnpython.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnpythonActionPerformed(evt);
            }
        });

        btnc.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnc.setForeground(new java.awt.Color(255, 0, 0));
        btnc.setText("C");
        btnc.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btncActionPerformed(evt);
            }
        });

        lblh1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblh1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblh1.setText("Click to view notes");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 0));
        jLabel1.setText("Enter fname");

        txtfname.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtfname.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtfname.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                txtfnameActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 0, 0));
        jLabel2.setText("Enter surname");

        txtlname.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtlname.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(115, 115, 115)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnjava, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnpython, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE)
                            .addComponent(btnc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(78, 78, 78)
                        .addComponent(lblh1, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtfname, javax.swing.GroupLayout.DEFAULT_SIZE, 131, Short.MAX_VALUE)
                            .addComponent(txtlname))))
                .addContainerGap(60, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtfname, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtlname, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(lblh1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(btnjava, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addComponent(btnpython, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(btnc, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnjavaActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnjavaActionPerformed
    {//GEN-HEADEREND:event_btnjavaActionPerformed
        // TODO add your handling code here:
        /*try
        {
            String sql;
            PreparedStatement st;
            ResultSet rs;
            Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/student","root","root");
            sql="select * from java where fname =? and lname =?";
            st=con.prepareStatement(sql);
            st.setString(1,txtfname.getText());
            st.setString(2,txtlname.getText());
            rs=st.executeQuery();
            if(rs.next())
            {
                sql="select path1 from javanotes limit 1";
                st=con.prepareStatement(sql);
                //st.setString(1,txtsearch.getText());
                rs=st.executeQuery();
                if(rs.next())
                {
                    String add1=rs.getString("path1");
                    Runtime rt=Runtime.getRuntime();
                    //String file="d:\\myfile.txt";
                    try
                    {
                        Process p=rt.exec("notepad "+add1);
                    } 
                    catch (IOException ex)
                    {
                        System.out.println("error"+ex);
                    }
                    //txtfname.setText(add1);
                    //String add2=rs.getString("lname");
                    //txtlname.setText(add2);
                }
            }    
            else
            {
                JOptionPane.showMessageDialog(null,"Not registerd for JAVA course contact center");
            }
        }
        catch(SQLException e)
        {
            System.out.println("error"+e);
        }*/
        try
        {
            String sql;
            PreparedStatement st;
            ResultSet rs;
            Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/student","root","root");
            sql="select * from java where fname =? and lname =?";
            st=con.prepareStatement(sql);
            st.setString(1,txtfname.getText());
            st.setString(2,txtlname.getText());
            rs=st.executeQuery();
            if(rs.next())
            {
                new javaselect().setVisible(true);
                dispose();
            }    
            else
            {
                JOptionPane.showMessageDialog(null,"Not registerd for JAVA course contact center");
            }
        }
        catch(SQLException e)
        {
            System.out.println("error"+e);
        }
        
    }//GEN-LAST:event_btnjavaActionPerformed

    private void btnpythonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnpythonActionPerformed
    {//GEN-HEADEREND:event_btnpythonActionPerformed
        // TODO add your handling code here:
        /*try
        {
            String sql;
            PreparedStatement st;
            ResultSet rs;
            Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/student","root","root");
            sql="select * from python where fname =? and lname =?";
            st=con.prepareStatement(sql);
            st.setString(1,txtfname.getText());
            st.setString(2,txtlname.getText());
            rs=st.executeQuery();
            if(rs.next())
            {
                sql="select path2 from pythonnotes limit 1";
                st=con.prepareStatement(sql);
                //st.setString(1,txtsearch.getText());
                rs=st.executeQuery();
                if(rs.next())
                {
                    String add1=rs.getString("path2");
                    Runtime rt=Runtime.getRuntime();
                    //String file="d:\\myfile.txt";
                    try
                    {
                        Process p=rt.exec("notepad "+add1);
                    } 
                    catch (IOException ex)
                    {
                        System.out.println("error"+ex);
                    }
                    //txtfname.setText(add1);
                    //String add2=rs.getString("lname");
                    //txtlname.setText(add2);
                }
            }    
            else
            {
                JOptionPane.showMessageDialog(null,"Not registerd for Python course contact center");
            }
        }
        catch(SQLException e)
        {
            System.out.println("error"+e);
        }*/
        try
        {
            String sql;
            PreparedStatement st;
            ResultSet rs;
            Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/student","root","root");
            sql="select * from python where fname =? and lname =?";
            st=con.prepareStatement(sql);
            st.setString(1,txtfname.getText());
            st.setString(2,txtlname.getText());
            rs=st.executeQuery();
            if(rs.next())
            {
                new pythonselect().setVisible(true);
                dispose();
            }    
            else
            {
                JOptionPane.showMessageDialog(null,"Not registerd for Python course contact center");
            }
        }
        catch(SQLException e)
        {
            System.out.println("error"+e);
        }
        
    }//GEN-LAST:event_btnpythonActionPerformed

    private void btncActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btncActionPerformed
    {//GEN-HEADEREND:event_btncActionPerformed
        // TODO add your handling code here:
        /*try
        {
            String sql;
            PreparedStatement st;
            ResultSet rs;
            Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/student","root","root");
            sql="select * from c where fname =? and lname =?";
            st=con.prepareStatement(sql);
            st.setString(1,txtfname.getText());
            st.setString(2,txtlname.getText());
            rs=st.executeQuery();
            if(rs.next())
            {
                sql="select path3 from cnotes limit 1";
                st=con.prepareStatement(sql);
                //st.setString(1,txtsearch.getText());
                rs=st.executeQuery();
                if(rs.next())
                {
                    String add1=rs.getString("path3");
                    Runtime rt=Runtime.getRuntime();
                    //String file="d:\\myfile.txt";
                    try
                    {
                        Process p=rt.exec("notepad "+add1);
                    } 
                    catch (IOException ex)
                    {
                        System.out.println("error"+ex);
                    }
                    //txtfname.setText(add1);
                    //String add2=rs.getString("lname");
                    //txtlname.setText(add2);
                }
            }    
            else
            {
                JOptionPane.showMessageDialog(null,"Not registerd for C course contact center");
            }
        }
        catch(SQLException e)
        {
            System.out.println("error"+e);
        }*/
        try
        {
            String sql;
            PreparedStatement st;
            ResultSet rs;
            Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/student","root","root");
            sql="select * from c where fname =? and lname =?";
            st=con.prepareStatement(sql);
            st.setString(1,txtfname.getText());
            st.setString(2,txtlname.getText());
            rs=st.executeQuery();
            if(rs.next())
            {
                new cselect().setVisible(true);
                dispose();
            }    
            else
            {
                JOptionPane.showMessageDialog(null,"Not registerd for C course contact center");
            }
        }
        catch(SQLException e)
        {
            System.out.println("error"+e);
        }
    }//GEN-LAST:event_btncActionPerformed

    private void txtfnameActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_txtfnameActionPerformed
    {//GEN-HEADEREND:event_txtfnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtfnameActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(Stu2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(Stu2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(Stu2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(Stu2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {
                new Stu2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnc;
    private javax.swing.JButton btnjava;
    private javax.swing.JButton btnpython;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblh1;
    private javax.swing.JTextField txtfname;
    private javax.swing.JTextField txtlname;
    // End of variables declaration//GEN-END:variables
}
